### PR TITLE
create a new customer for the invoice

### LINKED ISSUE #43: Create new costumer
**Issue Requirements**
The user can create a new customer for the invoice

**API Documentation**
Check the POST METHOD  `Create New Customer`.
Endpoint: `/api/v2/costumers`

### PR DESCRIPTION
**Pull request by DoaaNassar1995dbnassar**
close #43

### CODE REVIEW

**Comment by AhmedHamdan54** [comment]
Thanks @DoaaNassar1995dbnassar for this PR

**Review by salahamassi — COMMENTED** [review]
we can extract this code to helper method

` final Map<String, String> headers = <String, String>{
        'Content-Type': 'application/json'
      };
      if (_token != null) {
        headers['Authorization'] = 'Bearer $_token';
      }`
      
```
Map<String, String> _buildHeaer(String? token) {
  final Map<String, String> headers = <String, String>{
  'Content-Type': 'application/json'
  };
  if (_token != null) {
      headers['Authorization'] = 'Bearer $_token';
  }
  return headers;
}

```

**Comment by salahamassi** [comment]
Why did you put the code related to the **Customer creation feature** inside the **Cart feature**  package?

@DoaaNassar1995dbnassar   you should create a new feature for customers and move all the files related to the customer creation feature from the cart package feature.

**Review by salahamassi — COMMENTED** [review]
on the Customer model why do you use Hive annotations?
while you are storing the customer object on the hive box as a map.

**Review by salahamassi — COMMENTED** [review]
instead of forbidenOperation  -> ForbiddenOperation

**Review by salahamassi — COMMENTED** [review]
did we really need this class "forbidenOperation"?

**Review by salahamassi — COMMENTED** [review]
Add customer dialog should be out of cart controller 
we should extract all widget code from controlelrs

**Review by salahamassi — COMMENTED** [review]
these helpers methods are already available on shared_helper.dart inside **test/invoice/helpers/shared_test_helper.dart** we should extract them to a new global helper file, not rewrite them on a new file


```
final Exception anyException = Exception();

typedef TryFunction = Future<dynamic> Function();

dynamic tryFunction(TryFunction function) async {
  dynamic expectedError;
  try {
    await function();
  } catch (error) {
    expectedError = error;
  }
  return expectedError;
}
```

and we can rename the file to **customer_test_helper** instead of  **shared_test_helper**

and  I believe we should compare all customer props, not just mobile_no, we can user [equatable](https://pub.dev/packages/equatable) package

**Review by salahamassi — COMMENTED** [review]
on the second test, the name should be 'retrieve delivers the found customers on non-empty cache'

**Review by salahamassi — COMMENTED** [review]
we don't need the third test because the customer store doesn't have the delete feature 😅

**Review by salahamassi — COMMENTED** [review]
load does not override anything from store customer,  so you should remove this override annotation.

**Comment by salahamassi** [comment]
Thanks for your contribution 🚀

**Pull request merged**
