### PR TITLE
home feature

### PR DESCRIPTION
**Pull request by MohammedAlimoor**
Solves #28 #27 #8 #20 

1. Local Database (Hive)
2. Tablet and Web UI design
3. Enable flutter web

### CODE REVIEW

**Comment by AhmedHamdan54** [comment]
Hello @MohammedAlimoor , thanks for this PR.
You need to do solve some issues in order to merge this PR: 

1. You didn't initialize Hive, so it will throw this error: 

>  Hive Error: You need to initialize Hive or provide a path to store the box.

In order to solve this error just add  `await Hive.initFlutter();` before line **12** in **init_app.dart**

2.There is an issue in the naming I think is even from the last PR I will check it, the folder features is named wrongly with a blank space (And it's saved as %20) so it will fail the project, and even you can't clone the project in github, see this example in the import to understand the issue.
image

3. The UI is overflowing, I didn't really understand what part of the UI you tried to make so I don't know how to help in this.
Screenshot_1634565306

4. We are using other folder structure, all the folder structures all the same and it will not impact anything in the app, so let's try to be in the same wave please, so the people that forked the project can't continue without issues, please change it so it matches  this folder structure
image

**Comment by AhmedHamdan54** [comment]
This PR solves #20 , and part of #17 because 17 is a task to complete the UI of the Home screen.

**Comment by AhmedHamdan54** [comment]
@salahamassi  
Yes the naming issue and moving of the folder is from your PR and I can't even pull to solve it can you solve it please?
image

**Comment by MohammedAlimoor** [comment]
@AhmedHamdan54  hi 
plz check ui mobile and web  and features  like  bout faker data  , and layers app

**Pull request merged**
