### PR TITLE
- add barcode scanner library

### PR DESCRIPTION
**Pull request by byshy**
# Description

Please include a summary of the change and which issue is fixed and List any dependencies that are required for this change..

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix 
- [x] New feature

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] My changes generate no new warnings on the project.

### CODE REVIEW

**Comment by AhmedHamdan54** [comment]
Hello @byshy  Thanks for this PR.

You need to solve the conflicts in 
lib/features/carts/presentation/controllers/carts_controller.dart
lib/features/home/presentation/widgets/header_home.dart
lib/main.dart

Get the latest version, and in the description of the PR with the template you need to put your info.

**Comment by ServeMe** [comment]
@byshy as I told you before there will be conflicts that may happen between your work and @Shatha-Naami work in this #35 so uncomment here work and commit
@Shatha-Naami please fix this in your next PR on #36

**Comment by AhmedHamdan54** [comment]
Solves #13

**Comment by AhmedHamdan54** [comment]
Please @byshy  check this PR to see how you have to document the PR
https://github.com/The-POS/The-POS-Flutter/pull/34

**Pull request merged**
