### PR TITLE
Products cache policy 

### PR DESCRIPTION
**Pull request by salahamassi**
**Hello again  👋🏼**

In this PR, I worked on products cache policy.

### Products cache policy: 

our cache policy is simply "remove products from the cache after x time interval"

so when we insert the product into the cache we also save the current time to shared preference to check the expiration of cache late on.

```
  Future<Iterable<int>> insertProducts(List<Product> products) async {
    final SharedPreferences sharedPreferences =
        await SharedPreferences.getInstance();
    sharedPreferences.setInt(
        cacheTimeKey, DateTime.now().millisecondsSinceEpoch);
    return productsBox.addAll(products);
  }

```

and when we retrieve the products from the cache, first of all, we check the expiration of the cache, and if the cache is expired we delete all the cache.

```
  Future<List<Product>> getProductsByGroupId(int groupId) async {
    final bool isCacheExpired = await _isCacheExpired();
    if (isCacheExpired) {
      await productsBox.deleteFromDisk();
      return <Product>[];
    } else {
      return productsBox.values
          .where((Product product) => product.groupId == groupId)
          .toList();
    }
  }
```
For more details please check the code changes section.

### issues to solve:

- product image caching. 

### Somethings to improve:
- improve UI code.
- write some unit tests for HomeLocalDataSource functionality and HomeRepository.
- try to merge my work on PR #11  with  @MohammedAlimoor  PR #26, or delete unused files from #11  PR.

### CODE REVIEW

**Comment by AhmedHamdan54** [comment]
Hi @salahamassi  Thanks for this PR, I will merge this PR but I think there are some things to improve.


1- Initialize the shared preferences in the `init_app.dart` file.
2- Let's try to make things cleaner, and put the Shared preference as a separate file with the name of PreferenceUtils per example and there get the instance and there put all the methods I will put an example so you get it more.

```

class PreferenceUtils {
  static const PREF_USER_NAME = 'userName';

  static Future<SharedPreferences> get _instance async =>
      prefs ??= await SharedPreferences.getInstance();
  static SharedPreferences? prefs;

  static Future<SharedPreferences> init() async {
    prefs = await _instance;
    return prefs!;
  }

  static String _getString(String key, [String? defValue]) {
    return prefs!.getString(key) ?? '';
  }

  static String getUserName() {
    return _getString(PREF_USER_NAME, null);
  }
}
```
3 - We are not currently checking if there is a connection and showing any message in case it is the first time with the app and it doesn't have something stored and also can't get from remote (offline)
(Note I saw that you and Mohamed used connectivity it doesn't show if there is an internet connection it is just telling you if the wifi or mobile is connected, you can check by making per example any request to per example google.


I really like the way you comment on your PR thanks and keep going !!

**Comment by AhmedHamdan54** [comment]
Update: Solves points 1 and 2 in the last commit that I did.
Check it @salahamassi  please so you get what I meant

**Comment by ServeMe** [comment]
@salahamassi did this issue solved by #30 ?

**Comment by ServeMe** [comment]
@salahamassi  Did this PR solved this issue #18 ?

**Comment by salahamassi** [comment]
> @salahamassi Did this PR solved this issue #18 ?

yes

**Comment by AhmedHamdan54** [comment]
Yes it solves it, I will close the issue, thanks @salahamassi

**Pull request merged**
